// 160+ World Currencies with country mapping
export const WORLD_CURRENCIES = [
  { code: 'USD', name: 'US Dollar', symbol: '$', country: 'United States' },
  { code: 'EUR', name: 'Euro', symbol: '€', country: 'European Union' },
  { code: 'GBP', name: 'British Pound', symbol: '£', country: 'United Kingdom' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', country: 'Japan' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', country: 'Australia' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', country: 'Canada' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', country: 'Switzerland' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', country: 'China' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', country: 'Sweden' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', country: 'New Zealand' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', country: 'Mexico' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', country: 'Singapore' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', country: 'Hong Kong' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', country: 'Norway' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', country: 'Denmark' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', country: 'Poland' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', country: 'Czech Republic' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', country: 'Hungary' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', country: 'Russia' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', country: 'Brazil' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', country: 'India' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', country: 'South Korea' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', country: 'South Africa' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', country: 'Turkey' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', country: 'United Arab Emirates' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', country: 'Saudi Arabia' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', country: 'Israel' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£', country: 'Egypt' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', country: 'Thailand' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', country: 'Malaysia' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', country: 'Indonesia' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', country: 'Philippines' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', country: 'Vietnam' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', country: 'Bulgaria' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', country: 'Romania' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', country: 'Croatia' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', country: 'Serbia' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', country: 'Ukraine' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', country: 'Chile' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', country: 'Argentina' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', country: 'Colombia' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', country: 'Peru' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', country: 'Uruguay' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', country: 'Bolivia' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', country: 'Paraguay' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', country: 'Venezuela' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', country: 'Guyana' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', country: 'Suriname' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', country: 'Falkland Islands' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', country: 'Ghana' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', country: 'Nigeria' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', country: 'Kenya' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', country: 'Uganda' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', country: 'Tanzania' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', country: 'Ethiopia' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', country: 'Morocco' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', country: 'Tunisia' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', country: 'Algeria' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', country: 'Libya' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', country: 'Sudan' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', country: 'Somalia' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', country: 'Djibouti' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', country: 'Eritrea' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', country: 'Rwanda' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', country: 'Burundi' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', country: 'Comoros' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', country: 'Madagascar' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', country: 'Mauritius' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', country: 'Seychelles' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', country: 'Malawi' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', country: 'Zambia' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$', country: 'Zimbabwe' },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', country: 'Botswana' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', country: 'Namibia' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', country: 'Eswatini' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', country: 'Lesotho' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', country: 'Angola' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', country: 'Mozambique' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', country: 'Central Africa' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', country: 'West Africa' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', country: 'French Pacific' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', country: 'Afghanistan' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', country: 'Pakistan' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', country: 'Bangladesh' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', country: 'Sri Lanka' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', country: 'Nepal' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', country: 'Bhutan' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: '.ރ', country: 'Maldives' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'Ks', country: 'Myanmar' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', country: 'Laos' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', country: 'Cambodia' },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', country: 'Brunei' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', country: 'Taiwan' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', country: 'Mongolia' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', country: 'Kazakhstan' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв', country: 'Uzbekistan' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'лв', country: 'Kyrgyzstan' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', country: 'Tajikistan' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', country: 'Turkmenistan' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', country: 'Azerbaijan' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', country: 'Georgia' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', country: 'Armenia' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', country: 'Belarus' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', country: 'Moldova' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', country: 'Albania' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', country: 'North Macedonia' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', country: 'Bosnia and Herzegovina' },
  { code: 'EUR', name: 'Euro', symbol: '€', country: 'Montenegro' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', country: 'Kosovo' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', country: 'Iceland' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', country: 'Fiji' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', country: 'Tonga' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'T', country: 'Samoa' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt', country: 'Vanuatu' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', country: 'Solomon Islands' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', country: 'Papua New Guinea' },
  { code: 'NCL', name: 'New Caledonian Franc', symbol: '₣', country: 'New Caledonia' },
  { code: 'CKD', name: 'Cook Islands Dollar', symbol: '$', country: 'Cook Islands' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', country: 'Nicaragua' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', country: 'Costa Rica' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', country: 'Panama' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', country: 'Guatemala' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', country: 'Belize' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', country: 'Honduras' },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: '₡', country: 'El Salvador' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', country: 'Dominican Republic' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', country: 'Haiti' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱', country: 'Cuba' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', country: 'Jamaica' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', country: 'Cayman Islands' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', country: 'Trinidad and Tobago' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', country: 'Barbados' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', country: 'Eastern Caribbean' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', country: 'Aruba' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', country: 'Curaçao' },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', country: 'Bermuda' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', country: 'Bahamas' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', country: 'Bahrain' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', country: 'Qatar' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', country: 'Kuwait' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', country: 'Oman' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', country: 'Jordan' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: '£', country: 'Lebanon' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', country: 'Syria' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', country: 'Iraq' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', country: 'Iran' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', country: 'Yemen' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', country: 'Liberia' },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', country: 'Sierra Leone' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', country: 'Guinea' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', country: 'Gambia' },
  { code: 'SEN', name: 'Senegalese Franc', symbol: 'F', country: 'Senegal' },
  { code: 'MLI', name: 'Malian Franc', symbol: 'F', country: 'Mali' },
  { code: 'BFA', name: 'Burkinabé Franc', symbol: 'F', country: 'Burkina Faso' },
  { code: 'NER', name: 'Nigerien Franc', symbol: 'F', country: 'Niger' },
  { code: 'CIV', name: 'Ivorian Franc', symbol: 'F', country: 'Ivory Coast' },
  { code: 'TGO', name: 'Togolese Franc', symbol: 'F', country: 'Togo' },
  { code: 'BEN', name: 'Beninese Franc', symbol: 'F', country: 'Benin' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', country: 'Cape Verde' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', country: 'São Tomé and Príncipe' },
  { code: 'GQE', name: 'Equatorial Guinean Ekwele', symbol: 'E', country: 'Equatorial Guinea' },
  { code: 'GAB', name: 'Gabonese Franc', symbol: 'F', country: 'Gabon' },
  { code: 'CMR', name: 'Cameroonian Franc', symbol: 'F', country: 'Cameroon' },
  { code: 'CAF', name: 'Central African Franc', symbol: 'F', country: 'Central African Republic' },
  { code: 'TCD', name: 'Chadian Franc', symbol: 'F', country: 'Chad' },
  { code: 'COG', name: 'Congolese Franc', symbol: 'F', country: 'Republic of the Congo' },
  { code: 'COD', name: 'Congolese Franc', symbol: 'FC', country: 'Democratic Republic of the Congo' }
];

export const POPULAR_LOCATIONS = [
  // North America
  'New York, USA', 'San Francisco, USA', 'Los Angeles, USA', 'Chicago, USA', 'Boston, USA', 'Seattle, USA', 'Austin, USA', 'Miami, USA',
  'Toronto, Canada', 'Vancouver, Canada', 'Montreal, Canada', 'Calgary, Canada', 'Ottawa, Canada',
  'Mexico City, Mexico', 'Guadalajara, Mexico', 'Monterrey, Mexico',
  
  // Europe
  'London, UK', 'Manchester, UK', 'Edinburgh, UK', 'Birmingham, UK',
  'Berlin, Germany', 'Munich, Germany', 'Frankfurt, Germany', 'Hamburg, Germany', 'Cologne, Germany',
  'Paris, France', 'Lyon, France', 'Marseille, France', 'Nice, France', 'Toulouse, France',
  'Amsterdam, Netherlands', 'Rotterdam, Netherlands', 'The Hague, Netherlands',
  'Zurich, Switzerland', 'Geneva, Switzerland', 'Basel, Switzerland', 'Bern, Switzerland',
  'Stockholm, Sweden', 'Gothenburg, Sweden', 'Malmö, Sweden',
  'Copenhagen, Denmark', 'Aarhus, Denmark', 'Odense, Denmark',
  'Oslo, Norway', 'Bergen, Norway', 'Trondheim, Norway',
  'Barcelona, Spain', 'Madrid, Spain', 'Valencia, Spain', 'Seville, Spain', 'Bilbao, Spain',
  'Milan, Italy', 'Rome, Italy', 'Naples, Italy', 'Turin, Italy', 'Florence, Italy',
  'Vienna, Austria', 'Salzburg, Austria', 'Graz, Austria',
  'Prague, Czech Republic', 'Brno, Czech Republic',
  'Warsaw, Poland', 'Krakow, Poland', 'Gdansk, Poland',
  'Budapest, Hungary', 'Debrecen, Hungary',
  'Dublin, Ireland', 'Cork, Ireland',
  'Brussels, Belgium', 'Antwerp, Belgium',
  'Luxembourg City, Luxembourg',
  'Lisbon, Portugal', 'Porto, Portugal',
  'Athens, Greece', 'Thessaloniki, Greece',
  'Istanbul, Turkey', 'Ankara, Turkey', 'Izmir, Turkey',
  
  // Asia Pacific
  'Tokyo, Japan', 'Osaka, Japan', 'Kyoto, Japan', 'Yokohama, Japan', 'Nagoya, Japan',
  'Seoul, South Korea', 'Busan, South Korea', 'Incheon, South Korea',
  'Beijing, China', 'Shanghai, China', 'Shenzhen, China', 'Guangzhou, China', 'Hangzhou, China', 'Chengdu, China',
  'Hong Kong', 'Macau',
  'Taipei, Taiwan', 'Kaohsiung, Taiwan', 'Taichung, Taiwan',
  'Singapore',
  
  // India - Comprehensive List
  'Mumbai, India', 'Delhi, India', 'Bangalore, India', 'Hyderabad, India', 'Chennai, India', 'Kolkata, India',
  'Pune, India', 'Ahmedabad, India', 'Jaipur, India', 'Surat, India', 'Lucknow, India', 'Kanpur, India',
  'Nagpur, India', 'Indore, India', 'Thane, India', 'Bhopal, India', 'Visakhapatnam, India', 'Pimpri-Chinchwad, India',
  'Patna, India', 'Vadodara, India', 'Ghaziabad, India', 'Ludhiana, India', 'Agra, India', 'Nashik, India',
  'Faridabad, India', 'Meerut, India', 'Rajkot, India', 'Kalyan-Dombivali, India', 'Vasai-Virar, India',
  'Varanasi, India', 'Srinagar, India', 'Aurangabad, India', 'Dhanbad, India', 'Amritsar, India',
  'Navi Mumbai, India', 'Allahabad, India', 'Ranchi, India', 'Howrah, India', 'Coimbatore, India',
  'Jabalpur, India', 'Gwalior, India', 'Vijayawada, India', 'Jodhpur, India', 'Madurai, India',
  'Raipur, India', 'Kota, India', 'Chandigarh, India', 'Guwahati, India', 'Solapur, India',
  'Hubli-Dharwad, India', 'Tiruchirappalli, India', 'Bareilly, India', 'Mysore, India', 'Tiruppur, India',
  'Gurgaon, India', 'Noida, India', 'Kochi, India', 'Thiruvananthapuram, India', 'Bhubaneswar, India',
  
  // Southeast Asia
  'Bangkok, Thailand', 'Chiang Mai, Thailand', 'Phuket, Thailand',
  'Kuala Lumpur, Malaysia', 'George Town, Malaysia', 'Johor Bahru, Malaysia',
  'Jakarta, Indonesia', 'Surabaya, Indonesia', 'Bandung, Indonesia', 'Medan, Indonesia',
  'Manila, Philippines', 'Cebu, Philippines', 'Davao, Philippines',
  'Ho Chi Minh City, Vietnam', 'Hanoi, Vietnam', 'Da Nang, Vietnam',
  'Yangon, Myanmar', 'Mandalay, Myanmar',
  'Phnom Penh, Cambodia', 'Siem Reap, Cambodia',
  'Vientiane, Laos',
  'Bandar Seri Begawan, Brunei',
  
  // Middle East & Africa
  'Dubai, UAE', 'Abu Dhabi, UAE', 'Sharjah, UAE',
  'Riyadh, Saudi Arabia', 'Jeddah, Saudi Arabia', 'Dammam, Saudi Arabia',
  'Doha, Qatar', 'Kuwait City, Kuwait', 'Manama, Bahrain', 'Muscat, Oman',
  'Tel Aviv, Israel', 'Jerusalem, Israel', 'Haifa, Israel',
  'Cairo, Egypt', 'Alexandria, Egypt', 'Giza, Egypt',
  'Cape Town, South Africa', 'Johannesburg, South Africa', 'Durban, South Africa', 'Pretoria, South Africa',
  'Lagos, Nigeria', 'Abuja, Nigeria', 'Kano, Nigeria',
  'Nairobi, Kenya', 'Mombasa, Kenya',
  'Addis Ababa, Ethiopia', 'Dar es Salaam, Tanzania', 'Kampala, Uganda',
  'Accra, Ghana', 'Casablanca, Morocco', 'Tunis, Tunisia', 'Algiers, Algeria',
  
  // South America
  'São Paulo, Brazil', 'Rio de Janeiro, Brazil', 'Brasília, Brazil', 'Salvador, Brazil', 'Fortaleza, Brazil',
  'Buenos Aires, Argentina', 'Córdoba, Argentina', 'Rosario, Argentina',
  'Santiago, Chile', 'Valparaíso, Chile',
  'Lima, Peru', 'Arequipa, Peru',
  'Bogotá, Colombia', 'Medellín, Colombia', 'Cali, Colombia',
  'Caracas, Venezuela', 'Maracaibo, Venezuela',
  'Quito, Ecuador', 'Guayaquil, Ecuador',
  'La Paz, Bolivia', 'Santa Cruz, Bolivia',
  'Montevideo, Uruguay',
  'Asunción, Paraguay',
  
  // Oceania
  'Sydney, Australia', 'Melbourne, Australia', 'Brisbane, Australia', 'Perth, Australia', 'Adelaide, Australia',
  'Auckland, New Zealand', 'Wellington, New Zealand', 'Christchurch, New Zealand',
  'Suva, Fiji', 'Port Moresby, Papua New Guinea'
];

export const getCurrencyByCountry = (location: string): string => {
  const countryToCurrency: { [key: string]: string } = {
    'USA': 'USD', 'United States': 'USD', 'New York': 'USD', 'San Francisco': 'USD', 'Los Angeles': 'USD',
    'UK': 'GBP', 'United Kingdom': 'GBP', 'London': 'GBP', 'Manchester': 'GBP', 'Edinburgh': 'GBP',
    'Germany': 'EUR', 'Berlin': 'EUR', 'Munich': 'EUR', 'Frankfurt': 'EUR', 'Hamburg': 'EUR',
    'France': 'EUR', 'Paris': 'EUR', 'Lyon': 'EUR', 'Marseille': 'EUR', 'Nice': 'EUR',
    'Japan': 'JPY', 'Tokyo': 'JPY', 'Osaka': 'JPY', 'Kyoto': 'JPY', 'Yokohama': 'JPY',
    'Australia': 'AUD', 'Sydney': 'AUD', 'Melbourne': 'AUD', 'Brisbane': 'AUD', 'Perth': 'AUD',
    'Canada': 'CAD', 'Toronto': 'CAD', 'Vancouver': 'CAD', 'Montreal': 'CAD', 'Calgary': 'CAD',
    'Switzerland': 'CHF', 'Zurich': 'CHF', 'Geneva': 'CHF', 'Basel': 'CHF', 'Bern': 'CHF',
    'Singapore': 'SGD', 'Hong Kong': 'HKD', 'Dubai': 'AED', 'UAE': 'AED',
    'Sweden': 'SEK', 'Stockholm': 'SEK', 'Gothenburg': 'SEK', 'Malmö': 'SEK',
    'Norway': 'NOK', 'Oslo': 'NOK', 'Bergen': 'NOK', 'Trondheim': 'NOK',
    'Denmark': 'DKK', 'Copenhagen': 'DKK', 'Aarhus': 'DKK', 'Odense': 'DKK',
    'Netherlands': 'EUR', 'Amsterdam': 'EUR', 'Rotterdam': 'EUR', 'The Hague': 'EUR',
    'Spain': 'EUR', 'Madrid': 'EUR', 'Barcelona': 'EUR', 'Valencia': 'EUR', 'Seville': 'EUR',
    'Italy': 'EUR', 'Rome': 'EUR', 'Milan': 'EUR', 'Naples': 'EUR', 'Turin': 'EUR',
    'China': 'CNY', 'Beijing': 'CNY', 'Shanghai': 'CNY', 'Shenzhen': 'CNY', 'Guangzhou': 'CNY',
    'India': 'INR', 'Mumbai': 'INR', 'Delhi': 'INR', 'Bangalore': 'INR', 'Chennai': 'INR',
    'Brazil': 'BRL', 'São Paulo': 'BRL', 'Rio de Janeiro': 'BRL', 'Brasília': 'BRL',
    'Mexico': 'MXN', 'Mexico City': 'MXN', 'Guadalajara': 'MXN', 'Monterrey': 'MXN',
    'South Korea': 'KRW', 'Seoul': 'KRW', 'Busan': 'KRW', 'Incheon': 'KRW',
    'Thailand': 'THB', 'Bangkok': 'THB', 'Chiang Mai': 'THB', 'Phuket': 'THB',
    'Malaysia': 'MYR', 'Kuala Lumpur': 'MYR', 'George Town': 'MYR', 'Johor Bahru': 'MYR',
    'Indonesia': 'IDR', 'Jakarta': 'IDR', 'Surabaya': 'IDR', 'Bandung': 'IDR',
    'Philippines': 'PHP', 'Manila': 'PHP', 'Cebu': 'PHP', 'Davao': 'PHP',
    'Vietnam': 'VND', 'Ho Chi Minh City': 'VND', 'Hanoi': 'VND', 'Da Nang': 'VND',
    'Taiwan': 'TWD', 'Taipei': 'TWD', 'Kaohsiung': 'TWD', 'Taichung': 'TWD',
    'New Zealand': 'NZD', 'Auckland': 'NZD', 'Wellington': 'NZD', 'Christchurch': 'NZD'
  };

  for (const [key, currency] of Object.entries(countryToCurrency)) {
    if (location.toLowerCase().includes(key.toLowerCase())) {
      return currency;
    }
  }
  
  return 'USD'; // Default fallback
};